### ISSUE TITLE
Replace JP farm in maps/farm

### ISSUE THREAD

**Issue by jamierichardson1980** [Krixx1337/KX-Maps#15]
Heya, the jp file in maps/misc (Tyria JP CHEST FarmStart-Metrica Province.txt) is more comprehensive than the one located in maps/farm, so was wondering if you might want to replace/consolidate it. The file in misc has way more chests/locations.

**Comment by Bloodmagicball** [comment]
Thanks for reminding me :D i wanted to do that for a long time. Now i changed it, now the File is located in the Farm folder as well. Thank you
